// ============================================================
// Ideal Values Database
// Research-based cephalometric and anthropometric norms
// by ethnicity and gender
// ============================================================
// Sources:
// - Farkas LG: Anthropometry of the Head and Face
// - Legan HL, Burstone CJ: Soft tissue cephalometric analysis
// - Arnett GW, Bergman RT: Facial keys to orthodontic diagnosis
// - Ricketts RM: Cephalometric analysis
// - McNamara JA: Cephalometric analysis
// - Various peer-reviewed studies on ethnic facial norms
// ============================================================

import type { Gender, Ethnicity } from "./types"

export interface IdealValue {
  min: number
  max: number
  ideal: number
  description: string
}

type MeasurementNorms = Record<string, IdealValue>

// Helper to create a complete set of norms for a given gender/ethnicity
function createFrontNorms(
  base: Partial<MeasurementNorms> & { lateral_canthal_tilt: IdealValue; nose_bridge_to_width: IdealValue }
): MeasurementNorms {
  const defaults: MeasurementNorms = {
    lateral_canthal_tilt: base.lateral_canthal_tilt,
    nose_bridge_to_width: base.nose_bridge_to_width,
    bitemporal_width: base.bitemporal_width ?? { min: 75, max: 88, ideal: 82, description: "Percentage ratio of bitemporal width to bizygomatic width" },
    cheekbone_height: base.cheekbone_height ?? { min: 45, max: 65, ideal: 55, description: "Percentage ratio of Cupid's Bow height to cheekbone line vs pupil line" },
    cupids_bow_depth: base.cupids_bow_depth ?? { min: 2, max: 5, ideal: 3.5, description: "Vertical distance between Cupid's bow and inner Cupid's bow in mm" },
    bigonial_width: base.bigonial_width ?? { min: 70, max: 85, ideal: 78, description: "Percentage ratio of upper jaw width to bizygomatic width" },
    jaw_slope: base.jaw_slope ?? { min: 55, max: 75, ideal: 65, description: "Average of left and right jaw angles" },
    middle_third: base.middle_third ?? { min: 30, max: 38, ideal: 34, description: "Percentage of middle facial third to total facial height" },
    eye_aspect_ratio: base.eye_aspect_ratio ?? { min: 2.0, max: 4.0, ideal: 3.0, description: "Average ratio of eye width (horizontal) to eye height (vertical)" },
    mouth_corner_position: base.mouth_corner_position ?? { min: 0, max: 5, ideal: 2, description: "Average vertical offset of mouth corners from the mouth middle horizontal line" },
    eye_separation_ratio: base.eye_separation_ratio ?? { min: 42, max: 52, ideal: 47, description: "Percentage ratio of interpupillary distance to bizygomatic width" },
    eyebrow_tilt: base.eyebrow_tilt ?? { min: 5, max: 20, ideal: 12, description: "Average acute angle of eyebrow tilt from horizontal" },
    lower_third: base.lower_third ?? { min: 32, max: 40, ideal: 36, description: "Percentage of lower facial third to total facial height" },
    face_width_to_height: base.face_width_to_height ?? { min: 0.75, max: 0.88, ideal: 0.82, description: "Ratio of bizygomatic width to facial height (Cupid's bow to brow midpoint)" },
    interpupillary_mouth_width: base.interpupillary_mouth_width ?? { min: 85, max: 105, ideal: 95, description: "Percentage ratio of mouth width to interpupillary distance" },
    jaw_frontal_angle: base.jaw_frontal_angle ?? { min: 100, max: 140, ideal: 120, description: "Angle between left and right lower jaw-to-chin lines" },
    intercanthal_nasal_width: base.intercanthal_nasal_width ?? { min: 0.90, max: 1.10, ideal: 1.00, description: "Ratio of nasal width to intercanthal distance" },
    top_third: base.top_third ?? { min: 28, max: 36, ideal: 32, description: "Percentage of upper facial third to total facial height" },
    one_eye_apart: base.one_eye_apart ?? { min: 0.90, max: 1.15, ideal: 1.00, description: "Ratio of intercanthal distance to average medial canthus-to-hood-end distance" },
    midface_ratio: base.midface_ratio ?? { min: 0.95, max: 1.10, ideal: 1.02, description: "Ratio of interpupillary distance to inner Cupid's bow height" },
    ipsilateral_alar_angle: base.ipsilateral_alar_angle ?? { min: 25, max: 40, ideal: 32, description: "Angle at nasal base between left and right eyelid hood ends" },
    mouth_width_to_nose_width: base.mouth_width_to_nose_width ?? { min: 1.30, max: 1.70, ideal: 1.50, description: "Ratio of mouth width to nose width" },
    total_facial_width_to_height: base.total_facial_width_to_height ?? { min: 1.15, max: 1.40, ideal: 1.28, description: "Ratio of total facial height to bizygomatic width" },
    chin_to_philtrum: base.chin_to_philtrum ?? { min: 1.80, max: 2.40, ideal: 2.10, description: "Ratio of chin height to philtrum length" },
    eyebrow_low_setedness: base.eyebrow_low_setedness ?? { min: 0.12, max: 0.22, ideal: 0.17, description: "Ratio of brow-to-pupil-midpoint distance to average eye height" },
    brow_length_to_face_width: base.brow_length_to_face_width ?? { min: 0.28, max: 0.38, ideal: 0.33, description: "Ratio of combined brow horizontal span to bizygomatic width" },
    nose_tip_position: base.nose_tip_position ?? { min: 3, max: 8, ideal: 5, description: "Distance from nasal base to nose bottom in mm" },
    deviation_iaa_jfa: base.deviation_iaa_jfa ?? { min: -10, max: 10, ideal: 0, description: "Difference between Jaw Frontal Angle and Ipsilateral Alar Angle (JFA - IAA)" },
    lower_lip_to_upper_lip: base.lower_lip_to_upper_lip ?? { min: 1.20, max: 1.80, ideal: 1.50, description: "Ratio of lower lip height to upper lip height" },
    lower_third_proportion: base.lower_third_proportion ?? { min: 30, max: 42, ideal: 36, description: "Percentage of upper lip height to lower face height" },
  }
  return defaults
}

function createSideNorms(
  base: Partial<MeasurementNorms> & { nasal_tip_angle: IdealValue }
): MeasurementNorms {
  const defaults: MeasurementNorms = {
    nasal_tip_angle: base.nasal_tip_angle,
    nasal_width_to_height: base.nasal_width_to_height ?? { min: 0.55, max: 0.75, ideal: 0.65, description: "Ratio of nasal width to nasal height" },
    upper_lip_s_line: base.upper_lip_s_line ?? { min: -2, max: 2, ideal: 0, description: "Upper lip position relative to S-line (mm)" },
    upper_lip_burstone: base.upper_lip_burstone ?? { min: -2, max: 3, ideal: 0.5, description: "Upper lip position relative to Burstone line (mm)" },
    nasal_projection: base.nasal_projection ?? { min: 0.55, max: 0.70, ideal: 0.63, description: "Ratio of nasal projection to nasal length" },
    nasofrontal_angle: base.nasofrontal_angle ?? { min: 115, max: 135, ideal: 125, description: "Angle between forehead and nasal bridge" },
    recession_frankfort: base.recession_frankfort ?? { min: -4, max: 4, ideal: 0, description: "Recession relative to Frankfort plane (mm)" },
    holdaway_h_line: base.holdaway_h_line ?? { min: -2, max: 4, ideal: 1, description: "Holdaway H-line measurement (mm)" },
    mentolabial_angle: base.mentolabial_angle ?? { min: 100, max: 130, ideal: 115, description: "Angle between lower lip and chin" },
    upper_forehead_slope: base.upper_forehead_slope ?? { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead in degrees" },
    facial_convexity_nasion: base.facial_convexity_nasion ?? { min: 155, max: 175, ideal: 165, description: "Facial convexity angle at nasion" },
    anterior_facial_depth: base.anterior_facial_depth ?? { min: 20, max: 40, ideal: 30, description: "Angle at subalare between tragus and orbitale (degrees)" },
    upper_lip_e_line: base.upper_lip_e_line ?? { min: -4, max: 2, ideal: -1, description: "Upper lip position relative to E-line (mm)" },
    submental_cervical_angle: base.submental_cervical_angle ?? { min: 80, max: 100, ideal: 90, description: "Angle between submental and cervical planes" },
    facial_depth_to_height: base.facial_depth_to_height ?? { min: 0.70, max: 0.85, ideal: 0.78, description: "Ratio of facial depth to facial height" },
    browridge_inclination: base.browridge_inclination ?? { min: 50, max: 70, ideal: 60, description: "Inclination angle of brow ridge" },
    total_facial_convexity: base.total_facial_convexity ?? { min: 155, max: 175, ideal: 165, description: "Total facial convexity angle" },
    facial_convexity_glabella: base.facial_convexity_glabella ?? { min: 160, max: 178, ideal: 169, description: "Facial convexity angle at glabella" },
    orbital_vector: base.orbital_vector ?? { min: -2, max: 4, ideal: 1, description: "Orbital vector measurement (mm)" },
    interior_midface_projection: base.interior_midface_projection ?? { min: 10, max: 20, ideal: 15, description: "Interior midface projection angle" },
    z_angle: base.z_angle ?? { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
    nose_tip_rotation: base.nose_tip_rotation ?? { min: 90, max: 115, ideal: 102, description: "Nose tip rotation angle" },
    nasolabial_angle: base.nasolabial_angle ?? { min: 90, max: 110, ideal: 100, description: "Angle between nose base and upper lip" },
    nasofacial_angle: base.nasofacial_angle ?? { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
    nasomental_angle: base.nasomental_angle ?? { min: 120, max: 135, ideal: 128, description: "Angle between nose and chin" },
    frankfort_tip_angle: base.frankfort_tip_angle ?? { min: 105, max: 125, ideal: 115, description: "Angle between Frankfort plane and nose tip" },
    lower_lip_s_line: base.lower_lip_s_line ?? { min: -2, max: 2, ideal: 0, description: "Lower lip position relative to S-line (mm)" },
    lower_lip_e_line: base.lower_lip_e_line ?? { min: -4, max: 2, ideal: -1, description: "Lower lip position relative to E-line (mm)" },
    lower_lip_burstone: base.lower_lip_burstone ?? { min: -2, max: 3, ideal: 0.5, description: "Lower lip position relative to Burstone line (mm)" },
    gonial_angle: base.gonial_angle ?? { min: 115, max: 135, ideal: 125, description: "Angle of the mandible at gonion" },
    mandibular_plane_angle: base.mandibular_plane_angle ?? { min: 20, max: 35, ideal: 28, description: "Angle of mandibular plane relative to horizontal" },
    ramus_to_mandible: base.ramus_to_mandible ?? { min: 0.55, max: 0.75, ideal: 0.65, description: "Ratio of ramus height to mandibular body length" },
    gonion_to_mouth: base.gonion_to_mouth ?? { min: 0.40, max: 0.55, ideal: 0.48, description: "Ratio of gonion-to-mouth distance to facial height" },
  }
  return defaults
}

// ============================================================
// FRONT PROFILE IDEAL VALUES
// ============================================================

export const FRONT_IDEALS: Record<Gender, Record<Ethnicity, MeasurementNorms>> = {
  male: {
    asian: createFrontNorms({
      lateral_canthal_tilt: { min: -2.57, max: 19.67, ideal: 8.55, description: "Lateral Canthal Tilt (degrees)" },
      nose_bridge_to_width: { min: 1.16, max: 3.04, ideal: 2.1, description: "Nose Bridge to Nose Width Ratio" },
      bitemporal_width: { min: 75, max: 88, ideal: 82, description: "Bitemporal Width (%)" },
      cheekbone_height: { min: 49.48, max: 133.52, ideal: 91.5, description: "Cheekbone Height (%)" },
      bigonial_width: { min: 68.55, max: 110.45, ideal: 89.5, description: "Bigonial Width (%)" },
      jaw_slope: { min: 115.51, max: 166.99, ideal: 141.25, description: "Jaw Slope - obtuse angle (degrees)" },
      eye_aspect_ratio: { min: 1.42, max: 4.88, ideal: 3.15, description: "Eye Aspect Ratio (width/height)" },
      eye_separation_ratio: { min: 37.38, max: 54.98, ideal: 46.18, description: "Eye Separation Ratio (%)" },
      face_width_to_height: { min: 1.52, max: 2.38, ideal: 1.95, description: "Face Width to Height Ratio (fWHR)" },
      jaw_frontal_angle: { min: 54.78, max: 124.22, ideal: 89.5, description: "Jaw Frontal Angle (degrees)" },
      ipsilateral_alar_angle: { min: 68.23, max: 106.77, ideal: 87.5, description: "Ipsilateral Alar Angle (degrees)" },
      mouth_width_to_nose_width: { min: 1.04, max: 1.80, ideal: 1.42, description: "Mouth Width to Nose Width Ratio" },
      total_facial_width_to_height: { min: 0.70, max: 0.82, ideal: 0.76, description: "Total Facial Width to Height Ratio" },
      chin_to_philtrum: { min: 0.78, max: 3.82, ideal: 2.3, description: "Chin to Philtrum Ratio" },
      eyebrow_low_setedness: { min: -1.96, max: 3.21, ideal: 0.625, description: "Eyebrow Low Setedness (ratio)" },
      brow_length_to_face_width: { min: 0.33, max: 1.12, ideal: 0.725, description: "Brow Length to Face Width Ratio" },
      lower_third_proportion: { min: 26.21, max: 38.29, ideal: 32.25, description: "Lower Third Proportion (%)" },
      midface_ratio: { min: 0.61, max: 1.34, ideal: 0.975, description: "Midface Ratio" },
      cupids_bow_depth: { min: -2.15, max: 8.53, ideal: 3.19, description: "Cupid's Bow Depth (mm)" },
      eyebrow_tilt: { min: -14.02, max: 31.52, ideal: 8.75, description: "Eyebrow Tilt (degrees)" },
      lower_lip_to_upper_lip: { min: -0.44, max: 4.04, ideal: 1.8, description: "Lower Lip to Upper Lip Ratio" },
      top_third: { min: 20.25, max: 42.75, ideal: 31.5, description: "Top Third (%)" },
      middle_third: { min: 22.74, max: 43.06, ideal: 32.9, description: "Middle Third (%)" },
      lower_third: { min: 25.78, max: 44.32, ideal: 35.05, description: "Lower Third (%)" },
      one_eye_apart: { min: 0.72, max: 1.53, ideal: 1.125, description: "One Eye Apart Test (ratio)" },
      interpupillary_mouth_width: { min: 37, max: 123, ideal: 80, description: "Interpupillary-Mouth Width Ratio (%)" },
      deviation_iaa_jfa: { min: -22.21, max: 22.32, ideal: 0.055, description: "Deviation of IAA & JFA (degrees)" },
      mouth_corner_position: { min: -12.94, max: 16.94, ideal: 2, description: "Mouth Corner Position (mm)" },
    }),
    caucasian: createFrontNorms({
      lateral_canthal_tilt: { min: 5, max: 12, ideal: 8.5, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.50, max: 0.70, ideal: 0.60, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 78, max: 90, ideal: 84, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.42, max: 0.55, ideal: 0.48, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.68, max: 0.82, ideal: 0.75, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 58, max: 78, ideal: 68, description: "Angle of jaw line relative to horizontal" },
      eye_aspect_ratio: { min: 0.28, max: 0.42, ideal: 0.35, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.40, max: 0.50, ideal: 0.45, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 8, max: 18, ideal: 13, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.72, max: 0.85, ideal: 0.78, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 105, max: 128, ideal: 116, description: "Angle of jaw at gonion in frontal view" },
      ipsilateral_alar_angle: { min: 28, max: 42, ideal: 35, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.40, max: 1.80, ideal: 1.60, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.70, max: 0.82, ideal: 0.76, description: "Ratio of total facial width to total facial height" },
      chin_to_philtrum: { min: 1.80, max: 2.50, ideal: 2.15, description: "Ratio of chin height to philtrum height" },
      eyebrow_low_setedness: { min: 0.10, max: 0.20, ideal: 0.15, description: "Distance from brow to eye as ratio" },
      brow_length_to_face_width: { min: 0.30, max: 0.40, ideal: 0.35, description: "Ratio of brow length to facial width" },
    }),
    black: createFrontNorms({
      lateral_canthal_tilt: { min: 3, max: 10, ideal: 6.5, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.45, max: 0.65, ideal: 0.55, description: "Ratio of nose bridge width to nose width" },
      cheekbone_height: { min: 0.45, max: 0.58, ideal: 0.52, description: "Ratio of cheekbone height to facial height" },
      cupids_bow_depth: { min: 2, max: 6, ideal: 4, description: "Depth of Cupid's bow" },
      bigonial_width: { min: 0.70, max: 0.85, ideal: 0.78, description: "Ratio of bigonial width to bizygomatic width" },
      eye_separation_ratio: { min: 0.42, max: 0.54, ideal: 0.48, description: "Ratio of intercanthal distance to facial width" },
      lower_third: { min: 0.33, max: 0.42, ideal: 0.37, description: "Ratio of lower facial third" },
      face_width_to_height: { min: 0.75, max: 0.88, ideal: 0.82, description: "Ratio of facial width to facial height" },
      interpupillary_mouth_width: { min: 80, max: 100, ideal: 90, description: "Ratio of mouth width to interpupillary distance" },
      jaw_frontal_angle: { min: 100, max: 122, ideal: 110, description: "Angle of jaw at gonion" },
      intercanthal_nasal_width: { min: 0.85, max: 1.05, ideal: 0.95, description: "Ratio of intercanthal distance to nasal width" },
      ipsilateral_alar_angle: { min: 22, max: 38, ideal: 30, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.20, max: 1.60, ideal: 1.40, description: "Ratio of mouth width to nose width" },
      chin_to_philtrum: { min: 1.70, max: 2.30, ideal: 2.00, description: "Ratio of chin height to philtrum height" },
      lower_third_proportion: { min: 0.33, max: 0.42, ideal: 0.37, description: "Proportion of lower third" },
    }),
    hispanic: createFrontNorms({
      lateral_canthal_tilt: { min: 4, max: 12, ideal: 8, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.50, max: 0.70, ideal: 0.60, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.76, max: 0.88, ideal: 0.82, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.44, max: 0.57, ideal: 0.50, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.69, max: 0.84, ideal: 0.76, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 56, max: 76, ideal: 66, description: "Angle of jaw line" },
      eye_aspect_ratio: { min: 0.29, max: 0.43, ideal: 0.36, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.41, max: 0.52, ideal: 0.46, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 6, max: 16, ideal: 11, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.73, max: 0.86, ideal: 0.80, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 102, max: 125, ideal: 113, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 26, max: 40, ideal: 33, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.30, max: 1.70, ideal: 1.50, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.71, max: 0.84, ideal: 0.77, description: "Ratio of total facial width to total facial height" },
      chin_to_philtrum: { min: 1.80, max: 2.40, ideal: 2.10, description: "Ratio of chin height to philtrum height" },
      eyebrow_low_setedness: { min: 0.11, max: 0.21, ideal: 0.16, description: "Distance from brow to eye as ratio" },
      brow_length_to_face_width: { min: 0.29, max: 0.39, ideal: 0.34, description: "Ratio of brow length to facial width" },
    }),
    middle_eastern: createFrontNorms({
      lateral_canthal_tilt: { min: 4, max: 11, ideal: 7.5, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.50, max: 0.70, ideal: 0.60, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.77, max: 0.89, ideal: 0.83, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.43, max: 0.56, ideal: 0.49, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.69, max: 0.83, ideal: 0.76, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 57, max: 77, ideal: 67, description: "Angle of jaw line" },
      eye_separation_ratio: { min: 0.40, max: 0.51, ideal: 0.45, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 7, max: 17, ideal: 12, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.73, max: 0.86, ideal: 0.79, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 103, max: 126, ideal: 114, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 27, max: 41, ideal: 34, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.35, max: 1.75, ideal: 1.55, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.71, max: 0.84, ideal: 0.77, description: "Ratio of total facial width to total facial height" },
      brow_length_to_face_width: { min: 0.29, max: 0.39, ideal: 0.34, description: "Ratio of brow length to facial width" },
    }),
    south_asian: createFrontNorms({
      lateral_canthal_tilt: { min: 4, max: 12, ideal: 8, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.48, max: 0.68, ideal: 0.58, description: "Ratio of nose bridge width to nose width" },
      cheekbone_height: { min: 0.44, max: 0.57, ideal: 0.50, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.70, max: 0.85, ideal: 0.77, description: "Ratio of bigonial width to bizygomatic width" },
      eye_aspect_ratio: { min: 0.30, max: 0.44, ideal: 0.37, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.42, max: 0.53, ideal: 0.47, description: "Ratio of intercanthal distance to facial width" },
      face_width_to_height: { min: 0.74, max: 0.87, ideal: 0.80, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 100, max: 124, ideal: 112, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 25, max: 39, ideal: 32, description: "Angle of alar base on one side" },
      total_facial_width_to_height: { min: 0.72, max: 0.85, ideal: 0.78, description: "Ratio of total facial width to total facial height" },
    }),
    mixed: createFrontNorms({
      lateral_canthal_tilt: { min: 4, max: 12, ideal: 8, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.50, max: 0.70, ideal: 0.60, description: "Ratio of nose bridge width to nose width" },
    }),
  },
  female: {
    asian: createFrontNorms({
      lateral_canthal_tilt: { min: 6, max: 14, ideal: 10, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.50, max: 0.70, ideal: 0.60, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.73, max: 0.86, ideal: 0.80, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.43, max: 0.56, ideal: 0.50, description: "Ratio of cheekbone height to facial height" },
      cupids_bow_depth: { min: 3, max: 6, ideal: 4.5, description: "Depth of Cupid's bow" },
      bigonial_width: { min: 0.65, max: 0.80, ideal: 0.72, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 60, max: 80, ideal: 70, description: "Angle of jaw line" },
      middle_third: { min: 0.30, max: 0.38, ideal: 0.34, description: "Ratio of middle facial third" },
      eye_aspect_ratio: { min: 0.32, max: 0.48, ideal: 0.40, description: "Ratio of eye height to eye width" },
      mouth_corner_position: { min: 0.38, max: 0.52, ideal: 0.45, description: "Vertical position of mouth corners" },
      eye_separation_ratio: { min: 0.40, max: 0.50, ideal: 0.45, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 8, max: 18, ideal: 13, description: "Angle of eyebrow tilt" },
      lower_third: { min: 0.30, max: 0.38, ideal: 0.34, description: "Ratio of lower facial third" },
      face_width_to_height: { min: 0.70, max: 0.83, ideal: 0.76, description: "Ratio of facial width to facial height" },
      interpupillary_mouth_width: { min: 85, max: 105, ideal: 95, description: "Ratio of mouth width to interpupillary distance" },
      jaw_frontal_angle: { min: 105, max: 128, ideal: 116, description: "Angle of jaw at gonion" },
      intercanthal_nasal_width: { min: 0.90, max: 1.10, ideal: 1.00, description: "Ratio of intercanthal distance to nasal width" },
      top_third: { min: 0.28, max: 0.36, ideal: 0.32, description: "Ratio of upper facial third" },
      one_eye_apart: { min: 0.90, max: 1.15, ideal: 1.00, description: "Ratio of interpupillary distance to one eye width" },
      midface_ratio: { min: 0.95, max: 1.10, ideal: 1.02, description: "Ratio of midface width to midface height" },
      ipsilateral_alar_angle: { min: 25, max: 38, ideal: 31, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.30, max: 1.70, ideal: 1.50, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.68, max: 0.80, ideal: 0.74, description: "Ratio of total facial width to total facial height" },
      chin_to_philtrum: { min: 1.70, max: 2.30, ideal: 2.00, description: "Ratio of chin height to philtrum height" },
      eyebrow_low_setedness: { min: 0.10, max: 0.20, ideal: 0.15, description: "Distance from brow to eye as ratio" },
      brow_length_to_face_width: { min: 0.28, max: 0.38, ideal: 0.33, description: "Ratio of brow length to facial width" },
      nose_tip_position: { min: 0.55, max: 0.70, ideal: 0.62, description: "Vertical position of nose tip" },
      deviation_iaa_jfa: { min: 0, max: 8, ideal: 3, description: "Deviation between IAA and JFA" },
      lower_lip_to_upper_lip: { min: 1.20, max: 1.80, ideal: 1.50, description: "Ratio of lower lip to upper lip height" },
      lower_third_proportion: { min: 0.30, max: 0.38, ideal: 0.34, description: "Proportion of lower third" },
    }),
    caucasian: createFrontNorms({
      lateral_canthal_tilt: { min: 6, max: 14, ideal: 10, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.48, max: 0.68, ideal: 0.58, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.75, max: 0.88, ideal: 0.82, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.40, max: 0.53, ideal: 0.46, description: "Ratio of cheekbone height to facial height" },
      cupids_bow_depth: { min: 3, max: 6, ideal: 4.5, description: "Depth of Cupid's bow" },
      bigonial_width: { min: 0.62, max: 0.78, ideal: 0.70, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 62, max: 82, ideal: 72, description: "Angle of jaw line" },
      eye_aspect_ratio: { min: 0.30, max: 0.45, ideal: 0.37, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.38, max: 0.48, ideal: 0.43, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 10, max: 20, ideal: 15, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.68, max: 0.82, ideal: 0.75, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 108, max: 130, ideal: 118, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 28, max: 42, ideal: 35, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.40, max: 1.80, ideal: 1.60, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.66, max: 0.80, ideal: 0.73, description: "Ratio of total facial width to total facial height" },
      chin_to_philtrum: { min: 1.70, max: 2.40, ideal: 2.05, description: "Ratio of chin height to philtrum height" },
      eyebrow_low_setedness: { min: 0.08, max: 0.18, ideal: 0.13, description: "Distance from brow to eye as ratio" },
      brow_length_to_face_width: { min: 0.30, max: 0.40, ideal: 0.35, description: "Ratio of brow length to facial width" },
    }),
    black: createFrontNorms({
      lateral_canthal_tilt: { min: 4, max: 12, ideal: 8, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.42, max: 0.62, ideal: 0.52, description: "Ratio of nose bridge width to nose width" },
      cheekbone_height: { min: 0.43, max: 0.56, ideal: 0.50, description: "Ratio of cheekbone height to facial height" },
      cupids_bow_depth: { min: 3, max: 7, ideal: 5, description: "Depth of Cupid's bow" },
      bigonial_width: { min: 0.65, max: 0.80, ideal: 0.72, description: "Ratio of bigonial width to bizygomatic width" },
      eye_separation_ratio: { min: 0.40, max: 0.52, ideal: 0.46, description: "Ratio of intercanthal distance to facial width" },
      lower_third: { min: 0.31, max: 0.40, ideal: 0.35, description: "Ratio of lower facial third" },
      face_width_to_height: { min: 0.72, max: 0.85, ideal: 0.78, description: "Ratio of facial width to facial height" },
      interpupillary_mouth_width: { min: 78, max: 98, ideal: 88, description: "Ratio of mouth width to interpupillary distance" },
      jaw_frontal_angle: { min: 102, max: 124, ideal: 112, description: "Angle of jaw at gonion" },
      intercanthal_nasal_width: { min: 0.82, max: 1.02, ideal: 0.92, description: "Ratio of intercanthal distance to nasal width" },
      ipsilateral_alar_angle: { min: 20, max: 36, ideal: 28, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.15, max: 1.55, ideal: 1.35, description: "Ratio of mouth width to nose width" },
      chin_to_philtrum: { min: 1.60, max: 2.20, ideal: 1.90, description: "Ratio of chin height to philtrum height" },
      lower_third_proportion: { min: 0.31, max: 0.40, ideal: 0.35, description: "Proportion of lower third" },
    }),
    hispanic: createFrontNorms({
      lateral_canthal_tilt: { min: 5, max: 13, ideal: 9, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.48, max: 0.68, ideal: 0.58, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.74, max: 0.86, ideal: 0.80, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.42, max: 0.55, ideal: 0.48, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.64, max: 0.80, ideal: 0.72, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 58, max: 78, ideal: 68, description: "Angle of jaw line" },
      eye_aspect_ratio: { min: 0.30, max: 0.44, ideal: 0.37, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.39, max: 0.50, ideal: 0.44, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 8, max: 18, ideal: 13, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.70, max: 0.84, ideal: 0.77, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 104, max: 126, ideal: 114, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 26, max: 40, ideal: 33, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.30, max: 1.70, ideal: 1.50, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.68, max: 0.82, ideal: 0.75, description: "Ratio of total facial width to total facial height" },
      chin_to_philtrum: { min: 1.70, max: 2.30, ideal: 2.00, description: "Ratio of chin height to philtrum height" },
      eyebrow_low_setedness: { min: 0.09, max: 0.19, ideal: 0.14, description: "Distance from brow to eye as ratio" },
      brow_length_to_face_width: { min: 0.29, max: 0.39, ideal: 0.34, description: "Ratio of brow length to facial width" },
    }),
    middle_eastern: createFrontNorms({
      lateral_canthal_tilt: { min: 5, max: 13, ideal: 9, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.48, max: 0.68, ideal: 0.58, description: "Ratio of nose bridge width to nose width" },
      bitemporal_width: { min: 0.75, max: 0.87, ideal: 0.81, description: "Ratio of bitemporal width to facial width" },
      cheekbone_height: { min: 0.41, max: 0.54, ideal: 0.47, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.64, max: 0.79, ideal: 0.71, description: "Ratio of bigonial width to bizygomatic width" },
      jaw_slope: { min: 60, max: 80, ideal: 70, description: "Angle of jaw line" },
      eye_separation_ratio: { min: 0.38, max: 0.49, ideal: 0.43, description: "Ratio of intercanthal distance to facial width" },
      eyebrow_tilt: { min: 9, max: 19, ideal: 14, description: "Angle of eyebrow tilt" },
      face_width_to_height: { min: 0.70, max: 0.84, ideal: 0.77, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 105, max: 128, ideal: 116, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 27, max: 41, ideal: 34, description: "Angle of alar base on one side" },
      mouth_width_to_nose_width: { min: 1.35, max: 1.75, ideal: 1.55, description: "Ratio of mouth width to nose width" },
      total_facial_width_to_height: { min: 0.68, max: 0.82, ideal: 0.75, description: "Ratio of total facial width to total facial height" },
      brow_length_to_face_width: { min: 0.29, max: 0.39, ideal: 0.34, description: "Ratio of brow length to facial width" },
    }),
    south_asian: createFrontNorms({
      lateral_canthal_tilt: { min: 5, max: 13, ideal: 9, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.46, max: 0.66, ideal: 0.56, description: "Ratio of nose bridge width to nose width" },
      cheekbone_height: { min: 0.42, max: 0.55, ideal: 0.48, description: "Ratio of cheekbone height to facial height" },
      bigonial_width: { min: 0.65, max: 0.80, ideal: 0.72, description: "Ratio of bigonial width to bizygomatic width" },
      eye_aspect_ratio: { min: 0.32, max: 0.46, ideal: 0.39, description: "Ratio of eye height to eye width" },
      eye_separation_ratio: { min: 0.40, max: 0.51, ideal: 0.45, description: "Ratio of intercanthal distance to facial width" },
      face_width_to_height: { min: 0.71, max: 0.85, ideal: 0.78, description: "Ratio of facial width to facial height" },
      jaw_frontal_angle: { min: 102, max: 125, ideal: 113, description: "Angle of jaw at gonion" },
      ipsilateral_alar_angle: { min: 25, max: 39, ideal: 32, description: "Angle of alar base on one side" },
      total_facial_width_to_height: { min: 0.69, max: 0.83, ideal: 0.76, description: "Ratio of total facial width to total facial height" },
    }),
    mixed: createFrontNorms({
      lateral_canthal_tilt: { min: 5, max: 13, ideal: 9, description: "Slight upward tilt of the lateral canthus" },
      nose_bridge_to_width: { min: 0.48, max: 0.68, ideal: 0.58, description: "Ratio of nose bridge width to nose width" },
    }),
  },
}

// ============================================================
// SIDE PROFILE IDEAL VALUES
// ============================================================

export const SIDE_IDEALS: Record<Gender, Record<Ethnicity, MeasurementNorms>> = {
  male: {
    asian: createSideNorms({
      nasal_tip_angle: { min: 65, max: 80, ideal: 72, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 118, max: 138, ideal: 128, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 85, max: 105, ideal: 95, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 62, max: 82, ideal: 72, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 52, max: 72, ideal: 62, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 6, max: 16, ideal: 11, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    caucasian: createSideNorms({
      nasal_tip_angle: { min: 68, max: 82, ideal: 75, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 115, max: 135, ideal: 125, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 90, max: 110, ideal: 100, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 120, max: 135, ideal: 128, description: "Angle between nose and chin" },
      gonial_angle: { min: 115, max: 135, ideal: 125, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 20, max: 35, ideal: 28, description: "Angle of mandibular plane" },
      z_angle: { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 90, max: 115, ideal: 102, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 155, max: 175, ideal: 165, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 155, max: 175, ideal: 165, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 160, max: 178, ideal: 169, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 50, max: 70, ideal: 60, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 100, max: 130, ideal: 115, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 105, max: 125, ideal: 115, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 10, max: 20, ideal: 15, description: "Interior midface projection angle" },
    }),
    black: createSideNorms({
      nasal_tip_angle: { min: 62, max: 78, ideal: 70, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 120, max: 140, ideal: 130, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 85, max: 105, ideal: 95, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 58, max: 78, ideal: 68, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 48, max: 68, ideal: 58, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 4, max: 14, ideal: 9, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    hispanic: createSideNorms({
      nasal_tip_angle: { min: 66, max: 80, ideal: 73, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 116, max: 136, ideal: 126, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 88, max: 108, ideal: 98, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 120, max: 136, ideal: 128, description: "Angle between nose and chin" },
      gonial_angle: { min: 116, max: 136, ideal: 126, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 20, max: 36, ideal: 28, description: "Angle of mandibular plane" },
      z_angle: { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 90, max: 116, ideal: 103, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 156, max: 176, ideal: 166, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 156, max: 176, ideal: 166, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 160, max: 179, ideal: 170, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 50, max: 70, ideal: 60, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 100, max: 130, ideal: 115, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 106, max: 126, ideal: 116, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 10, max: 20, ideal: 15, description: "Interior midface projection angle" },
    }),
    middle_eastern: createSideNorms({
      nasal_tip_angle: { min: 66, max: 80, ideal: 73, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 114, max: 134, ideal: 124, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 88, max: 108, ideal: 98, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 120, max: 135, ideal: 128, description: "Angle between nose and chin" },
      gonial_angle: { min: 115, max: 135, ideal: 125, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 20, max: 35, ideal: 28, description: "Angle of mandibular plane" },
      z_angle: { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 90, max: 115, ideal: 102, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 155, max: 175, ideal: 165, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 155, max: 175, ideal: 165, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 160, max: 178, ideal: 169, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 50, max: 70, ideal: 60, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 100, max: 130, ideal: 115, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 105, max: 125, ideal: 115, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 10, max: 20, ideal: 15, description: "Interior midface projection angle" },
    }),
    south_asian: createSideNorms({
      nasal_tip_angle: { min: 64, max: 78, ideal: 71, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 118, max: 138, ideal: 128, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 86, max: 106, ideal: 96, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 30, max: 40, ideal: 35, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 50, max: 70, ideal: 60, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    mixed: createSideNorms({
      nasal_tip_angle: { min: 66, max: 80, ideal: 73, description: "Angle of the nasal tip" },
    }),
  },
  female: {
    asian: createSideNorms({
      nasal_tip_angle: { min: 68, max: 84, ideal: 76, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 120, max: 140, ideal: 130, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 92, max: 112, ideal: 102, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 124, max: 140, ideal: 132, description: "Angle between nose and chin" },
      gonial_angle: { min: 120, max: 140, ideal: 130, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 24, max: 40, ideal: 32, description: "Angle of mandibular plane" },
      z_angle: { min: 64, max: 84, ideal: 74, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 95, max: 120, ideal: 108, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 160, max: 180, ideal: 170, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 160, max: 180, ideal: 170, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 164, max: 182, ideal: 173, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 48, max: 68, ideal: 58, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 6, max: 16, ideal: 11, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 104, max: 134, ideal: 119, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 110, max: 130, ideal: 120, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 14, max: 24, ideal: 19, description: "Interior midface projection angle" },
    }),
    caucasian: createSideNorms({
      nasal_tip_angle: { min: 70, max: 86, ideal: 78, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 118, max: 138, ideal: 128, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 95, max: 115, ideal: 105, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 62, max: 82, ideal: 72, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 46, max: 66, ideal: 56, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    black: createSideNorms({
      nasal_tip_angle: { min: 65, max: 80, ideal: 72, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 122, max: 142, ideal: 132, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 88, max: 108, ideal: 98, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 34, max: 44, ideal: 39, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 124, max: 140, ideal: 132, description: "Angle between nose and chin" },
      gonial_angle: { min: 120, max: 140, ideal: 130, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 24, max: 40, ideal: 32, description: "Angle of mandibular plane" },
      z_angle: { min: 60, max: 80, ideal: 70, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 95, max: 120, ideal: 108, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 160, max: 180, ideal: 170, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 160, max: 180, ideal: 170, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 164, max: 182, ideal: 173, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 44, max: 64, ideal: 54, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 4, max: 14, ideal: 9, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 104, max: 134, ideal: 119, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 110, max: 130, ideal: 120, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 14, max: 24, ideal: 19, description: "Interior midface projection angle" },
    }),
    hispanic: createSideNorms({
      nasal_tip_angle: { min: 68, max: 84, ideal: 76, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 118, max: 138, ideal: 128, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 92, max: 112, ideal: 102, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 62, max: 82, ideal: 72, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 46, max: 66, ideal: 56, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    middle_eastern: createSideNorms({
      nasal_tip_angle: { min: 68, max: 84, ideal: 76, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 116, max: 136, ideal: 126, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 92, max: 112, ideal: 102, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 122, max: 138, ideal: 130, description: "Angle between nose and chin" },
      gonial_angle: { min: 118, max: 138, ideal: 128, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 22, max: 38, ideal: 30, description: "Angle of mandibular plane" },
      z_angle: { min: 62, max: 82, ideal: 72, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 92, max: 118, ideal: 105, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 158, max: 178, ideal: 168, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 158, max: 178, ideal: 168, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 162, max: 180, ideal: 171, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 46, max: 66, ideal: 56, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 102, max: 132, ideal: 117, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 108, max: 128, ideal: 118, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 12, max: 22, ideal: 17, description: "Interior midface projection angle" },
    }),
    south_asian: createSideNorms({
      nasal_tip_angle: { min: 66, max: 82, ideal: 74, description: "Angle of the nasal tip" },
      nasofrontal_angle: { min: 120, max: 140, ideal: 130, description: "Angle between forehead and nasal bridge" },
      nasolabial_angle: { min: 90, max: 110, ideal: 100, description: "Angle between nose base and upper lip" },
      nasofacial_angle: { min: 32, max: 42, ideal: 37, description: "Angle between nasal bridge and facial plane" },
      nasomental_angle: { min: 124, max: 140, ideal: 132, description: "Angle between nose and chin" },
      gonial_angle: { min: 120, max: 140, ideal: 130, description: "Angle of the mandible at gonion" },
      mandibular_plane_angle: { min: 24, max: 40, ideal: 32, description: "Angle of mandibular plane" },
      z_angle: { min: 62, max: 82, ideal: 72, description: "Z-angle of soft tissue profile" },
      nose_tip_rotation: { min: 95, max: 120, ideal: 108, description: "Nose tip rotation angle" },
      facial_convexity_nasion: { min: 160, max: 180, ideal: 170, description: "Facial convexity angle at nasion" },
      total_facial_convexity: { min: 160, max: 180, ideal: 170, description: "Total facial convexity angle" },
      facial_convexity_glabella: { min: 164, max: 182, ideal: 173, description: "Facial convexity angle at glabella" },
      browridge_inclination: { min: 46, max: 66, ideal: 56, description: "Inclination angle of brow ridge" },
      upper_forehead_slope: { min: 5, max: 15, ideal: 10, description: "Slope of upper forehead" },
      mentolabial_angle: { min: 104, max: 134, ideal: 119, description: "Angle between lower lip and chin" },
      frankfort_tip_angle: { min: 110, max: 130, ideal: 120, description: "Angle between Frankfort plane and nose tip" },
      interior_midface_projection: { min: 14, max: 24, ideal: 19, description: "Interior midface projection angle" },
    }),
    mixed: createSideNorms({
      nasal_tip_angle: { min: 68, max: 84, ideal: 76, description: "Angle of the nasal tip" },
    }),
  },
}

// ============================================================
// Helper to get ideal values for a specific measurement
// ============================================================

export function getIdealValue(
  measurementId: string,
  gender: Gender,
  ethnicity: Ethnicity,
  profileType: "front" | "side"
): IdealValue | null {
  const ideals = profileType === "front" ? FRONT_IDEALS : SIDE_IDEALS
  const genderIdeals = ideals[gender]
  if (!genderIdeals) return null
  const ethnicityIdeals = genderIdeals[ethnicity]
  if (!ethnicityIdeals) return null
  return ethnicityIdeals[measurementId] ?? null
}

// ============================================================
// Measurement metadata for display
// ============================================================

export interface MeasurementMeta {
  id: string
  name: string
  unit: "degrees" | "ratio" | "mm" | "percentage"
  category: string
  description: string
}

export const FRONT_MEASUREMENTS_META: MeasurementMeta[] = [
  { id: "lateral_canthal_tilt", name: "Lateral Canthal Tilt", unit: "degrees", category: "Eyes", description: "Angle of upward tilt from medial to lateral canthus" },
  { id: "nose_bridge_to_width", name: "Nose Bridge to Nose Width", unit: "ratio", category: "Nose", description: "Ratio of nose bridge width to total nose width" },
  { id: "bitemporal_width", name: "Bitemporal Width", unit: "percentage", category: "Head", description: "Percentage ratio of bitemporal width to bizygomatic width" },
  { id: "cheekbone_height", name: "Cheekbone Height", unit: "percentage", category: "Cheeks", description: "Percentage ratio of Cupid's Bow distance to cheekbone line vs pupil line" },
  { id: "cupids_bow_depth", name: "Cupid's Bow Depth", unit: "mm", category: "Mouth", description: "Vertical distance between Cupid's bow and inner Cupid's bow" },
  { id: "bigonial_width", name: "Bigonial Width", unit: "percentage", category: "Jaw", description: "Percentage ratio of upper jaw angle width to bizygomatic width" },
  { id: "jaw_slope", name: "Jaw Slope", unit: "degrees", category: "Jaw", description: "Average of left and right jaw angles" },
  { id: "middle_third", name: "Middle Third", unit: "percentage", category: "Proportions", description: "Percentage of middle facial third to total facial height" },
  { id: "eye_aspect_ratio", name: "Eye Aspect Ratio", unit: "ratio", category: "Eyes", description: "Average ratio of eye width (horizontal) to eye height (vertical)" },
  { id: "mouth_corner_position", name: "Mouth Corner Position", unit: "mm", category: "Mouth", description: "Average vertical offset of mouth corners from mouth middle line" },
  { id: "eye_separation_ratio", name: "Eye Separation Ratio", unit: "percentage", category: "Eyes", description: "Percentage ratio of interpupillary distance to bizygomatic width" },
  { id: "eyebrow_tilt", name: "Eyebrow Tilt", unit: "degrees", category: "Brows", description: "Average acute angle of eyebrow tilt from horizontal" },
  { id: "lower_third", name: "Lower Third", unit: "percentage", category: "Proportions", description: "Percentage of lower facial third to total facial height" },
  { id: "face_width_to_height", name: "Face Width to Height Ratio", unit: "ratio", category: "Proportions", description: "Ratio of bizygomatic width to facial height (Cupid's bow to brow midpoint)" },
  { id: "interpupillary_mouth_width", name: "Interpupillary-Mouth Width Ratio", unit: "percentage", category: "Proportions", description: "Percentage ratio of mouth width to interpupillary distance" },
  { id: "jaw_frontal_angle", name: "Jaw Frontal Angle", unit: "degrees", category: "Jaw", description: "Angle between left and right lower jaw-to-chin lines" },
  { id: "intercanthal_nasal_width", name: "Intercanthal-Nasal Width Ratio", unit: "ratio", category: "Nose", description: "Ratio of nasal width to intercanthal distance" },
  { id: "top_third", name: "Top Third", unit: "percentage", category: "Proportions", description: "Percentage of upper facial third relative to total facial height" },
  { id: "one_eye_apart", name: "One Eye Apart Test", unit: "ratio", category: "Eyes", description: "Ratio of intercanthal distance to average eyelid hood distance" },
  { id: "midface_ratio", name: "Midface Ratio", unit: "ratio", category: "Proportions", description: "Ratio of interpupillary distance to inner Cupid's bow height" },
  { id: "ipsilateral_alar_angle", name: "Ipsilateral Alar Angle", unit: "degrees", category: "Nose", description: "Angle at nasal base between left and right eyelid hood ends" },
  { id: "mouth_width_to_nose_width", name: "Mouth Width to Nose Width Ratio", unit: "ratio", category: "Mouth", description: "Ratio of mouth width to nose width" },
  { id: "total_facial_width_to_height", name: "Total Facial Width to Height Ratio", unit: "ratio", category: "Proportions", description: "Ratio of total facial height to bizygomatic width" },
  { id: "chin_to_philtrum", name: "Chin to Philtrum Ratio", unit: "ratio", category: "Chin", description: "Ratio of chin height to philtrum length" },
  { id: "eyebrow_low_setedness", name: "Eyebrow Low Setedness", unit: "ratio", category: "Brows", description: "Ratio of brow-to-pupil-midpoint distance to average eye height" },
  { id: "brow_length_to_face_width", name: "Brow Length to Face Width Ratio", unit: "ratio", category: "Brows", description: "Ratio of combined brow horizontal span to bizygomatic width" },
  { id: "nose_tip_position", name: "Nose Tip Position", unit: "mm", category: "Nose", description: "Distance from nasal base to nose bottom" },
  { id: "deviation_iaa_jfa", name: "Deviation of IAA & JFA", unit: "degrees", category: "Proportions", description: "Difference between Jaw Frontal Angle and Ipsilateral Alar Angle (JFA - IAA)" },
  { id: "lower_lip_to_upper_lip", name: "Lower Lip to Upper Lip Ratio", unit: "ratio", category: "Mouth", description: "Ratio of lower lip height to upper lip height" },
  { id: "lower_third_proportion", name: "Lower Third Proportion", unit: "percentage", category: "Proportions", description: "Percentage of upper lip height to lower face height" },
]

export const SIDE_MEASUREMENTS_META: MeasurementMeta[] = [
  { id: "nasal_tip_angle", name: "Nasal Tip Angle", unit: "degrees", category: "Nose", description: "Angle of the nasal tip" },
  { id: "nasal_width_to_height", name: "Nasal Width to Height Ratio", unit: "ratio", category: "Nose", description: "Ratio of nasal width to nasal height" },
  { id: "upper_lip_s_line", name: "Upper Lip S-Line Position", unit: "mm", category: "Lips", description: "Upper lip position relative to S-line" },
  { id: "upper_lip_burstone", name: "Upper Lip Burstone Line", unit: "mm", category: "Lips", description: "Upper lip position relative to Burstone line" },
  { id: "nasal_projection", name: "Nasal Projection", unit: "ratio", category: "Nose", description: "Ratio of nasal width (subalare to nose tip) to nasal height (nose tip to nasion)" },
  { id: "nasofrontal_angle", name: "Nasofrontal Angle", unit: "degrees", category: "Nose", description: "Angle between forehead and nasal bridge" },
  { id: "recession_frankfort", name: "Recession (Frankfort Plane)", unit: "mm", category: "Profile", description: "Recession relative to Frankfort plane" },
  { id: "holdaway_h_line", name: "Holdaway H Line", unit: "mm", category: "Profile", description: "Holdaway H-line measurement" },
  { id: "mentolabial_angle", name: "Mentolabial Angle", unit: "degrees", category: "Chin", description: "Angle between lower lip and chin" },
  { id: "upper_forehead_slope", name: "Upper Forehead Slope", unit: "degrees", category: "Forehead", description: "Slope of upper forehead" },
  { id: "facial_convexity_nasion", name: "Facial Convexity (Nasion)", unit: "degrees", category: "Profile", description: "Facial convexity angle at nasion" },
  { id: "anterior_facial_depth", name: "Anterior Facial Depth", unit: "degrees", category: "Proportions", description: "Angle at subalare between tragus and orbitale" },
  { id: "upper_lip_e_line", name: "Upper Lip E-Line Position", unit: "mm", category: "Lips", description: "Upper lip position relative to E-line" },
  { id: "submental_cervical_angle", name: "Submental Cervical Angle", unit: "degrees", category: "Neck", description: "Angle between submental and cervical planes" },
  { id: "facial_depth_to_height", name: "Facial Depth to Height Ratio", unit: "ratio", category: "Proportions", description: "Ratio of facial depth to facial height" },
  { id: "browridge_inclination", name: "Browridge Inclination Angle", unit: "degrees", category: "Brows", description: "Inclination angle of brow ridge" },
  { id: "total_facial_convexity", name: "Total Facial Convexity", unit: "degrees", category: "Profile", description: "Total facial convexity angle" },
  { id: "facial_convexity_glabella", name: "Facial Convexity (Glabella)", unit: "degrees", category: "Profile", description: "Facial convexity angle at glabella" },
  { id: "orbital_vector", name: "Orbital Vector", unit: "mm", category: "Eyes", description: "Orbital vector measurement" },
  { id: "interior_midface_projection", name: "Interior Midface Projection Angle", unit: "degrees", category: "Midface", description: "Interior midface projection angle" },
  { id: "z_angle", name: "Z Angle", unit: "degrees", category: "Profile", description: "Z-angle of soft tissue profile" },
  { id: "nose_tip_rotation", name: "Nose Tip Rotation Angle", unit: "degrees", category: "Nose", description: "Nose tip rotation angle" },
  { id: "nasolabial_angle", name: "Nasolabial Angle", unit: "degrees", category: "Nose", description: "Angle between nose base and upper lip" },
  { id: "nasofacial_angle", name: "Nasofacial Angle", unit: "degrees", category: "Nose", description: "Angle between nasal bridge and facial plane" },
  { id: "nasomental_angle", name: "Nasomental Angle", unit: "degrees", category: "Profile", description: "Angle between nose and chin" },
  { id: "frankfort_tip_angle", name: "Frankfort-Tip Angle", unit: "degrees", category: "Nose", description: "Angle between Frankfort plane and nose tip" },
  { id: "lower_lip_s_line", name: "Lower Lip S-Line Position", unit: "mm", category: "Lips", description: "Lower lip position relative to S-line" },
  { id: "lower_lip_e_line", name: "Lower Lip E-Line Position", unit: "mm", category: "Lips", description: "Lower lip position relative to E-line" },
  { id: "lower_lip_burstone", name: "Lower Lip Burstone Line", unit: "mm", category: "Lips", description: "Lower lip position relative to Burstone line" },
  { id: "gonial_angle", name: "Gonial Angle", unit: "degrees", category: "Jaw", description: "Angle of the mandible at gonion" },
  { id: "mandibular_plane_angle", name: "Mandibular Plane Angle", unit: "degrees", category: "Jaw", description: "Angle of mandibular plane relative to horizontal" },
  { id: "ramus_to_mandible", name: "Ramus to Mandible Ratio", unit: "ratio", category: "Jaw", description: "Ratio of ramus height to mandibular body length" },
  { id: "gonion_to_mouth", name: "Gonion to Mouth Line", unit: "ratio", category: "Jaw", description: "Ratio of gonion-to-mouth distance to facial height" },
]




