// Simulated facial analysis data for each hero sample image
// Each entry represents a unique "person" with realistic facial metrics

export interface SampleAnalysis {
  id: number
  image: string
  name: string
  overallScore: number
  overallPercentile: string
  overallLabel: string
  frontProfile: number
  frontLabel: string
  sideProfile: number
  sideLabel: string
  symmetry: number
  symmetryLabel: string
  proportions: number
  proportionsLabel: string
  jawAngle: number
  jawLabel: string
  nasalProjection: number
  nasalLabel: string
  eyeSpacing: number
  eyeLabel: string
  midfaceHarmony: number
  midfaceLabel: string
  strengths: string[]
  focusAreas: string[]
  measurements: {
    label: string
    value: string
    ideal: string
    status: "good" | "warning" | "attention"
  }[]
}

export const sampleAnalyses: SampleAnalysis[] = [
  {
    id: 1,
    image: "/hero-samples/sample-1.jpg",
    name: "Sample A",
    overallScore: 7.4,
    overallPercentile: "Top 12%",
    overallLabel: "Excellent balance",
    frontProfile: 7.8,
    frontLabel: "Strong mid‑face harmony",
    sideProfile: 7.0,
    sideLabel: "Room for profile refinement",
    symmetry: 8.1,
    symmetryLabel: "Highly symmetrical",
    proportions: 7.2,
    proportionsLabel: "Well‑balanced thirds",
    jawAngle: 6.8,
    jawLabel: "Moderate definition",
    nasalProjection: 7.5,
    nasalLabel: "Good projection",
    eyeSpacing: 8.3,
    eyeLabel: "Ideal spacing",
    midfaceHarmony: 7.6,
    midfaceLabel: "Strong midface",
    strengths: [
      "Balanced facial thirds",
      "Favorable eye spacing",
      "Strong chin projection",
    ],
    focusAreas: [
      "Mild jaw angle asymmetry",
      "Slight nasal projection imbalance",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.02:0.98", ideal: "1:1:1", status: "good" },
      { label: "Eye Spacing Index", value: "46.2%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "132°", ideal: "130–135°", status: "good" },
      { label: "Nasolabial Angle", value: "108°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "112°", ideal: "115–120°", status: "warning" },
      { label: "Chin-to-Neck Angle", value: "88°", ideal: "85–92°", status: "good" },
    ],
  },
  {
    id: 2,
    image: "/hero-samples/sample-2.jpg",
    name: "Sample B",
    overallScore: 6.8,
    overallPercentile: "Top 28%",
    overallLabel: "Above average harmony",
    frontProfile: 7.0,
    frontLabel: "Good frontal balance",
    sideProfile: 6.5,
    sideLabel: "Moderate profile concerns",
    symmetry: 7.2,
    symmetryLabel: "Minor asymmetry",
    proportions: 6.9,
    proportionsLabel: "Slightly uneven thirds",
    jawAngle: 6.2,
    jawLabel: "Narrower jaw definition",
    nasalProjection: 7.0,
    nasalLabel: "Adequate projection",
    eyeSpacing: 7.8,
    eyeLabel: "Good spacing",
    midfaceHarmony: 6.5,
    midfaceLabel: "Average midface",
    strengths: [
      "Pleasant eye symmetry",
      "Good nasal tip rotation",
      "Balanced lip proportions",
    ],
    focusAreas: [
      "Jaw width below average",
      "Midface slightly long",
      "Profile angle could improve",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.08:0.95", ideal: "1:1:1", status: "warning" },
      { label: "Eye Spacing Index", value: "45.8%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "128°", ideal: "130–135°", status: "warning" },
      { label: "Nasolabial Angle", value: "112°", ideal: "95–110°", status: "warning" },
      { label: "Jaw Angle Width", value: "108°", ideal: "115–120°", status: "attention" },
      { label: "Chin-to-Neck Angle", value: "84°", ideal: "85–92°", status: "warning" },
    ],
  },
  {
    id: 3,
    image: "/hero-samples/sample-3.jpg",
    name: "Sample C",
    overallScore: 8.2,
    overallPercentile: "Top 5%",
    overallLabel: "Exceptional harmony",
    frontProfile: 8.5,
    frontLabel: "Excellent frontal symmetry",
    sideProfile: 7.9,
    sideLabel: "Well‑defined profile",
    symmetry: 8.7,
    symmetryLabel: "Near‑perfect symmetry",
    proportions: 8.3,
    proportionsLabel: "Ideal facial thirds",
    jawAngle: 8.0,
    jawLabel: "Strong jaw definition",
    nasalProjection: 8.4,
    nasalLabel: "Excellent projection",
    eyeSpacing: 8.6,
    eyeLabel: "Ideal spacing",
    midfaceHarmony: 8.1,
    midfaceLabel: "Excellent midface",
    strengths: [
      "Exceptional facial symmetry",
      "Ideal jaw-to-face ratio",
      "Perfect nasal projection",
      "Well‑defined cheekbones",
    ],
    focusAreas: [
      "Minor chin asymmetry",
      "Slight brow ridge prominence",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.01:0.99", ideal: "1:1:1", status: "good" },
      { label: "Eye Spacing Index", value: "46.8%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "133°", ideal: "130–135°", status: "good" },
      { label: "Nasolabial Angle", value: "102°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "118°", ideal: "115–120°", status: "good" },
      { label: "Chin-to-Neck Angle", value: "90°", ideal: "85–92°", status: "good" },
    ],
  },
  {
    id: 4,
    image: "/hero-samples/sample-4.jpg",
    name: "Sample D",
    overallScore: 6.2,
    overallPercentile: "Top 40%",
    overallLabel: "Average harmony",
    frontProfile: 6.5,
    frontLabel: "Moderate frontal balance",
    sideProfile: 5.8,
    sideLabel: "Profile needs attention",
    symmetry: 6.8,
    symmetryLabel: "Noticeable asymmetry",
    proportions: 6.0,
    proportionsLabel: "Uneven facial thirds",
    jawAngle: 5.5,
    jawLabel: "Weak jaw definition",
    nasalProjection: 6.2,
    nasalLabel: "Below average projection",
    eyeSpacing: 7.0,
    eyeLabel: "Adequate spacing",
    midfaceHarmony: 5.8,
    midfaceLabel: "Below average midface",
    strengths: [
      "Pleasant eye shape",
      "Good lip volume",
      "Harmonious brow arch",
    ],
    focusAreas: [
      "Jaw angle significantly narrow",
      "Midface elongation",
      "Nasal projection below ideal",
      "Profile angle needs improvement",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.12:0.92", ideal: "1:1:1", status: "attention" },
      { label: "Eye Spacing Index", value: "43.5%", ideal: "44–48%", status: "warning" },
      { label: "Nasofrontal Angle", value: "124°", ideal: "130–135°", status: "attention" },
      { label: "Nasolabial Angle", value: "118°", ideal: "95–110°", status: "attention" },
      { label: "Jaw Angle Width", value: "104°", ideal: "115–120°", status: "attention" },
      { label: "Chin-to-Neck Angle", value: "80°", ideal: "85–92°", status: "attention" },
    ],
  },
  {
    id: 5,
    image: "/hero-samples/sample-5.jpg",
    name: "Sample E",
    overallScore: 7.8,
    overallPercentile: "Top 8%",
    overallLabel: "Very good harmony",
    frontProfile: 8.0,
    frontLabel: "Excellent frontal view",
    sideProfile: 7.5,
    sideLabel: "Good profile definition",
    symmetry: 8.2,
    symmetryLabel: "Highly symmetrical",
    proportions: 7.8,
    proportionsLabel: "Well‑balanced",
    jawAngle: 7.5,
    jawLabel: "Good jaw definition",
    nasalProjection: 7.8,
    nasalLabel: "Strong projection",
    eyeSpacing: 8.4,
    eyeLabel: "Ideal spacing",
    midfaceHarmony: 7.6,
    midfaceLabel: "Strong midface",
    strengths: [
      "Excellent eye symmetry",
      "Well‑defined cheekbones",
      "Balanced lip-to-chin ratio",
      "Good jawline contour",
    ],
    focusAreas: [
      "Slight nasal tip deviation",
      "Minor brow asymmetry",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.03:0.97", ideal: "1:1:1", status: "good" },
      { label: "Eye Spacing Index", value: "47.2%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "131°", ideal: "130–135°", status: "good" },
      { label: "Nasolabial Angle", value: "106°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "116°", ideal: "115–120°", status: "good" },
      { label: "Chin-to-Neck Angle", value: "87°", ideal: "85–92°", status: "good" },
    ],
  },
  {
    id: 6,
    image: "/hero-samples/sample-6.jpg",
    name: "Sample F",
    overallScore: 7.1,
    overallPercentile: "Top 20%",
    overallLabel: "Good overall harmony",
    frontProfile: 7.3,
    frontLabel: "Good frontal balance",
    sideProfile: 6.8,
    sideLabel: "Moderate profile",
    symmetry: 7.5,
    symmetryLabel: "Minor asymmetry",
    proportions: 7.0,
    proportionsLabel: "Slightly uneven",
    jawAngle: 6.8,
    jawLabel: "Average jaw definition",
    nasalProjection: 7.2,
    nasalLabel: "Adequate projection",
    eyeSpacing: 7.6,
    eyeLabel: "Good spacing",
    midfaceHarmony: 6.9,
    midfaceLabel: "Average midface",
    strengths: [
      "Good eye symmetry",
      "Pleasant nasal shape",
      "Balanced lip proportions",
    ],
    focusAreas: [
      "Jaw angle slightly narrow",
      "Midface length slightly long",
      "Chin projection could improve",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.06:0.96", ideal: "1:1:1", status: "warning" },
      { label: "Eye Spacing Index", value: "45.0%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "129°", ideal: "130–135°", status: "warning" },
      { label: "Nasolabial Angle", value: "110°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "110°", ideal: "115–120°", status: "warning" },
      { label: "Chin-to-Neck Angle", value: "83°", ideal: "85–92°", status: "warning" },
    ],
  },
  {
    id: 7,
    image: "/hero-samples/sample-7.jpg",
    name: "Sample G",
    overallScore: 8.5,
    overallPercentile: "Top 3%",
    overallLabel: "Outstanding harmony",
    frontProfile: 8.7,
    frontLabel: "Exceptional frontal view",
    sideProfile: 8.2,
    sideLabel: "Excellent profile",
    symmetry: 9.0,
    symmetryLabel: "Near‑perfect symmetry",
    proportions: 8.6,
    proportionsLabel: "Ideal proportions",
    jawAngle: 8.3,
    jawLabel: "Excellent jaw definition",
    nasalProjection: 8.5,
    nasalLabel: "Perfect projection",
    eyeSpacing: 8.8,
    eyeLabel: "Ideal spacing",
    midfaceHarmony: 8.4,
    midfaceLabel: "Exceptional midface",
    strengths: [
      "Near‑perfect facial symmetry",
      "Ideal facial third proportions",
      "Excellent jaw definition",
      "Perfect nasal profile",
      "Well‑defined cheekbones",
    ],
    focusAreas: [
      "Very minor lip asymmetry",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.00:1.00", ideal: "1:1:1", status: "good" },
      { label: "Eye Spacing Index", value: "47.5%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "134°", ideal: "130–135°", status: "good" },
      { label: "Nasolabial Angle", value: "104°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "119°", ideal: "115–120°", status: "good" },
      { label: "Chin-to-Neck Angle", value: "91°", ideal: "85–92°", status: "good" },
    ],
  },
  {
    id: 8,
    image: "/hero-samples/sample-8.jpg",
    name: "Sample H",
    overallScore: 6.5,
    overallPercentile: "Top 35%",
    overallLabel: "Above average",
    frontProfile: 6.8,
    frontLabel: "Moderate frontal balance",
    sideProfile: 6.2,
    sideLabel: "Profile needs work",
    symmetry: 6.5,
    symmetryLabel: "Asymmetry present",
    proportions: 6.3,
    proportionsLabel: "Uneven thirds",
    jawAngle: 5.8,
    jawLabel: "Narrow jaw",
    nasalProjection: 6.5,
    nasalLabel: "Average projection",
    eyeSpacing: 7.2,
    eyeLabel: "Adequate spacing",
    midfaceHarmony: 6.0,
    midfaceLabel: "Below average",
    strengths: [
      "Pleasant eye shape",
      "Good brow structure",
      "Harmonious lip shape",
    ],
    focusAreas: [
      "Jaw width significantly below ideal",
      "Midface elongation",
      "Nasal projection below average",
      "Profile angle needs improvement",
      "Chin retrusion",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.10:0.93", ideal: "1:1:1", status: "attention" },
      { label: "Eye Spacing Index", value: "44.2%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "126°", ideal: "130–135°", status: "attention" },
      { label: "Nasolabial Angle", value: "115°", ideal: "95–110°", status: "attention" },
      { label: "Jaw Angle Width", value: "106°", ideal: "115–120°", status: "attention" },
      { label: "Chin-to-Neck Angle", value: "78°", ideal: "85–92°", status: "attention" },
    ],
  },
  {
    id: 9,
    image: "/hero-samples/sample-9.jpg",
    name: "Sample I",
    overallScore: 7.6,
    overallPercentile: "Top 10%",
    overallLabel: "Very good harmony",
    frontProfile: 7.9,
    frontLabel: "Strong frontal view",
    sideProfile: 7.2,
    sideLabel: "Good profile",
    symmetry: 7.8,
    symmetryLabel: "Good symmetry",
    proportions: 7.5,
    proportionsLabel: "Well‑balanced",
    jawAngle: 7.2,
    jawLabel: "Good jaw definition",
    nasalProjection: 7.6,
    nasalLabel: "Strong projection",
    eyeSpacing: 8.0,
    eyeLabel: "Ideal spacing",
    midfaceHarmony: 7.4,
    midfaceLabel: "Good midface",
    strengths: [
      "Good facial symmetry",
      "Well‑defined cheekbones",
      "Ideal eye spacing",
      "Strong chin projection",
    ],
    focusAreas: [
      "Slight jaw angle asymmetry",
      "Minor nasal deviation",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.04:0.97", ideal: "1:1:1", status: "good" },
      { label: "Eye Spacing Index", value: "46.5%", ideal: "44–48%", status: "good" },
      { label: "Nasofrontal Angle", value: "132°", ideal: "130–135°", status: "good" },
      { label: "Nasolabial Angle", value: "107°", ideal: "95–110°", status: "good" },
      { label: "Jaw Angle Width", value: "114°", ideal: "115–120°", status: "warning" },
      { label: "Chin-to-Neck Angle", value: "86°", ideal: "85–92°", status: "good" },
    ],
  },
  {
    id: 10,
    image: "/hero-samples/sample-10.jpg",
    name: "Sample J",
    overallScore: 5.8,
    overallPercentile: "Top 50%",
    overallLabel: "Average range",
    frontProfile: 6.0,
    frontLabel: "Moderate frontal view",
    sideProfile: 5.5,
    sideLabel: "Profile needs attention",
    symmetry: 6.2,
    symmetryLabel: "Asymmetry present",
    proportions: 5.6,
    proportionsLabel: "Uneven proportions",
    jawAngle: 5.2,
    jawLabel: "Weak jaw definition",
    nasalProjection: 5.8,
    nasalLabel: "Below average",
    eyeSpacing: 6.5,
    eyeLabel: "Slightly narrow",
    midfaceHarmony: 5.4,
    midfaceLabel: "Below average",
    strengths: [
      "Pleasant eye shape",
      "Good lip volume",
      "Harmonious brow shape",
    ],
    focusAreas: [
      "Jaw angle significantly narrow",
      "Midface elongation",
      "Nasal projection below ideal",
      "Profile angle needs improvement",
      "Chin retrusion",
      "Eye spacing slightly narrow",
    ],
    measurements: [
      { label: "Facial Thirds Ratio", value: "1:1.14:0.90", ideal: "1:1:1", status: "attention" },
      { label: "Eye Spacing Index", value: "42.8%", ideal: "44–48%", status: "attention" },
      { label: "Nasofrontal Angle", value: "122°", ideal: "130–135°", status: "attention" },
      { label: "Nasolabial Angle", value: "120°", ideal: "95–110°", status: "attention" },
      { label: "Jaw Angle Width", value: "102°", ideal: "115–120°", status: "attention" },
      { label: "Chin-to-Neck Angle", value: "76°", ideal: "85–92°", status: "attention" },
    ],
  },
]
